name: SonarQube analysis

on:
  pull_request:
    branches:
      - '**'

jobs:
  sonarqube:
    name: Analyze on SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:ci

      - name: Cache SonarQube Scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: verify coverage file is generated
        run: |
          ls -l coverage
          head -n 10 coverage/lcov.info
        
          
      - name: Run SonarQube scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      #✅ Check unit test coverage >= 95%
      - name: Check unit test coverage >= 95%
        run: |
          COVERAGE=$(grep -A1 "All files" coverage/lcov-report/index.html | grep -Eo '[0-9]+\.[0-9]+%' | head -n 1 | sed 's/%//')
          echo "Statements coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 95" | bc -l) )); then
            echo "❌ Unit test coverage is below 90%"
            exit 1
          else
            echo "✅ Coverage is sufficient"
          fi

      - name: run e2e tests
        run: npm run cy:run
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      
        
        
        
