name: Run tests before merge into master

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
 
      - name: Replace Firebase keys in environment.ts
        run: |
          sed -i 's|firebase: {.*}|firebase: { apiKey: "$FIREBASE_API_KEY", authDomain: "$FIREBASE_AUTH_DOMAIN", projectId: "$FIREBASE_PROJECT_ID", storageBucket: "$FIREBASE_STORAGE_BUCKET", messagingSenderId: "$FIREBASE_MESSAGING_SENDER_ID", appId: "$FIREBASE_APP_ID" }|' src/environments/environment.ts

      - name: Run unit tests
        run: npm run test 

      - name: Check coverage file
        run: ls -l coverage && cat coverage/lcov.info | head -n 10

      - name: Run e2e tests
        run: npm run cy:run
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=joselarcu
            -Dsonar.projectKey=Joselarcu_recipe-finder
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}